#!/bin/sh
# This shell script is PUBLIC DOMAIN. You may do whatever you want with it.

TOGGLE=$HOME/.mako_dnd_toggle

if [ ! -e $TOGGLE ]
then
	touch $TOGGLE
	makoctl mode -a do-not-disturb
else
	rm $TOGGLE
	makoctl mode -r do-not-disturb
fi
