#!/bin/sh

NOTEDIR=$HOME/Notes/

if [ -z $EDITOR ]; then
	EDITOR=vim
fi

if [ ! -d $NOTEDIR ]; then
	echo "Directory ~/Notes does not exist, create it? [y/N]"
	# TODO do input n stuff, good shit
	echo "But I haven't implemented this yet lol."
	exit 1
fi

if [ $# -eq 0 ]; then
	# Escaped version for sed
	NOTEDIRESC=$(echo $NOTEDIR | sed 's/\//\\\//g')
	result=$(fd . $NOTEDIR | sed "s/$NOTEDIRESC//" | fzf)

	# Only open editor if they selected an option
	if [ -z $result ]; then
		exit 0
	fi
	$EDITOR "$NOTEDIR$result"
else
	$EDITOR "$NOTEDIR$(date '+%Y-%m-%d')-$1.txt"
fi

exit 0
