#!/bin/bash

if tmux list-sessions &> /dev/null
then
	tmux list-sessions
	echo "---"
	echo "Use 'tmux attach -t <name>' to attach to a session,"
	echo "(or 'tmux new -s <name>' to create a new session.)"
else
	echo "No tmux sessions running."
	echo "---"
	echo "Use 'tmux new -s <name>' to create a new session."
fi
